name: Send Feedback to Jules
description: 'Checks if a PR review is from an allowed user and sends the feedback to Jules.'
branding:
  icon: 'message-square'
  color: 'purple'

inputs:
  jules_api_key:
    description: 'The Jules API key to use for authentication'
    required: true
  feedback_users:
    description: 'Comma-separated list of GitHub usernames authorized to provide feedback'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check and Send Feedback
      uses: actions/github-script@v7
      env:
        JULES_API_KEY: ${{ inputs.jules_api_key }}
        FEEDBACK_USERS: ${{ inputs.feedback_users }}
      with:
        script: |
          const pr = context.payload.pull_request;
          const review = context.payload.review;
          const reviewer = context.payload.sender.login;
          const prBody = pr.body || "";

          // 1. Check if Jules PR
          // Look for pattern: "PR created automatically by Jules for task [ID](url) started by @user"
          const regex = /PR created automatically by Jules for task \[([0-9]+)\]\(.*\) started by @([\w-]+)/;
          const match = prBody.match(regex);

          if (!match) {
            console.log("Not a Jules PR. Skipping.");
            return;
          }

          const sessionId = match[1];
          const starter = match[2];

          console.log(`Jules Session ID: ${sessionId}`);
          console.log(`Starter: ${starter}`);
          console.log(`Reviewer: ${reviewer}`);

          // 2. Check if Reviewer is Starter
          if (reviewer === starter) {
            console.log("Reviewer is the starter. Skipping.");
            return;
          }

          // 3. Check Allowed Users
          const feedbackUsersString = process.env.FEEDBACK_USERS || "";
          const feedbackUsers = feedbackUsersString.split(',').map(u => u.trim()).filter(u => u.length > 0);

          if (feedbackUsers.length === 0) {
              console.log("Skipping: FEEDBACK_USERS input is empty.");
              return;
          }

          if (!feedbackUsers.includes(reviewer)) {
              console.log(`User ${reviewer} is not in the allowed FEEDBACK_USERS list.`);
              return;
          }

          console.log(`User ${reviewer} is authorized to provide feedback.`);

          // 4. Gather Feedback
          let feedback = "";
          if (review.body) {
            feedback += `Review Summary:\n${review.body}\n\n`;
          }

          // Fetch review comments (line comments) associated with this review
          try {
            const { data: comments } = await github.rest.pulls.listReviewComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              review_id: review.id
            });

            if (comments && comments.length > 0) {
              feedback += "Line Comments:\n";
              comments.forEach(c => {
                  feedback += `File: ${c.path}:${c.original_line || c.line}\n`;
                  feedback += `Comment: ${c.body}\n\n`;
              });
            }
          } catch (err) {
              console.log(`Warning: Failed to fetch review comments: ${err.message}`);
          }

          if (!feedback.trim()) {
              console.log("No feedback content found (empty review body and no comments).");
              return;
          }

          console.log("Sending feedback to Jules...");

          const julesApiKey = process.env.JULES_API_KEY;
          if (!julesApiKey) {
              core.setFailed("JULES_API_KEY input is not set.");
              return;
          }

          const url = `https://jules.googleapis.com/v1alpha/sessions/${sessionId}:sendMessage`;
          const payload = {
              prompt: `Feedback from ${reviewer}:\n\n${feedback}`
          };

          // Use native fetch (available in Node 20 environment of actions/github-script@v7)
          const response = await fetch(url, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'X-Goog-Api-Key': julesApiKey
            },
            body: JSON.stringify(payload)
          });

          if (!response.ok) {
            const errorText = await response.text();
            core.setFailed(`Jules API Error: ${response.status} ${response.statusText} - ${errorText}`);
            return;
          }

          console.log("Feedback successfully sent to Jules.");
